/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AuthRouteImport } from './pages/_auth'
import { Route as AuthCodeLoginRouteImport } from './pages/_auth/code-login'
import { Route as AuthForgetPasswordRouteImport } from './pages/_auth/forget-password'
import { Route as AuthLoginRouteImport } from './pages/_auth/login'
import { Route as AuthQrcodeLoginRouteImport } from './pages/_auth/qrcode-login'
import { Route as AuthRegisterRouteImport } from './pages/_auth/register'
import { Route as DashboardIndexRouteImport } from './pages/dashboard/index'
import { Route as ExamplesLexicalRouteImport } from './pages/examples/lexical'
import { Route as ExamplesSlateRouteImport } from './pages/examples/slate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCodeLoginRoute = AuthCodeLoginRouteImport.update({
  id: '/code-login',
  path: '/code-login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgetPasswordRoute = AuthForgetPasswordRouteImport.update({
  id: '/forget-password',
  path: '/forget-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQrcodeLoginRoute = AuthQrcodeLoginRouteImport.update({
  id: '/qrcode-login',
  path: '/qrcode-login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesLexicalRoute = ExamplesLexicalRouteImport.update({
  id: '/examples/lexical',
  path: '/examples/lexical',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSlateRoute = ExamplesSlateRouteImport.update({
  id: '/examples/slate',
  path: '/examples/slate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-login': typeof AuthCodeLoginRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/qrcode-login': typeof AuthQrcodeLoginRoute
  '/register': typeof AuthRegisterRoute
  '/examples/lexical': typeof ExamplesLexicalRoute
  '/examples/slate': typeof ExamplesSlateRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-login': typeof AuthCodeLoginRoute
  '/forget-password': typeof AuthForgetPasswordRoute
  '/login': typeof AuthLoginRoute
  '/qrcode-login': typeof AuthQrcodeLoginRoute
  '/register': typeof AuthRegisterRoute
  '/examples/lexical': typeof ExamplesLexicalRoute
  '/examples/slate': typeof ExamplesSlateRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/code-login': typeof AuthCodeLoginRoute
  '/_auth/forget-password': typeof AuthForgetPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/qrcode-login': typeof AuthQrcodeLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/examples/lexical': typeof ExamplesLexicalRoute
  '/examples/slate': typeof ExamplesSlateRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code-login'
    | '/forget-password'
    | '/login'
    | '/qrcode-login'
    | '/register'
    | '/examples/lexical'
    | '/examples/slate'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code-login'
    | '/forget-password'
    | '/login'
    | '/qrcode-login'
    | '/register'
    | '/examples/lexical'
    | '/examples/slate'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/code-login'
    | '/_auth/forget-password'
    | '/_auth/login'
    | '/_auth/qrcode-login'
    | '/_auth/register'
    | '/examples/lexical'
    | '/examples/slate'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ExamplesLexicalRoute: typeof ExamplesLexicalRoute
  ExamplesSlateRoute: typeof ExamplesSlateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/code-login': {
      id: '/_auth/code-login'
      path: '/code-login'
      fullPath: '/code-login'
      preLoaderRoute: typeof AuthCodeLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forget-password': {
      id: '/_auth/forget-password'
      path: '/forget-password'
      fullPath: '/forget-password'
      preLoaderRoute: typeof AuthForgetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/qrcode-login': {
      id: '/_auth/qrcode-login'
      path: '/qrcode-login'
      fullPath: '/qrcode-login'
      preLoaderRoute: typeof AuthQrcodeLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/lexical': {
      id: '/examples/lexical'
      path: '/examples/lexical'
      fullPath: '/examples/lexical'
      preLoaderRoute: typeof ExamplesLexicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/slate': {
      id: '/examples/slate'
      path: '/examples/slate'
      fullPath: '/examples/slate'
      preLoaderRoute: typeof ExamplesSlateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCodeLoginRoute: typeof AuthCodeLoginRoute
  AuthForgetPasswordRoute: typeof AuthForgetPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthQrcodeLoginRoute: typeof AuthQrcodeLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCodeLoginRoute: AuthCodeLoginRoute,
  AuthForgetPasswordRoute: AuthForgetPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthQrcodeLoginRoute: AuthQrcodeLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ExamplesLexicalRoute: ExamplesLexicalRoute,
  ExamplesSlateRoute: ExamplesSlateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
