name: Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JavaScript
        uses: sxzz/workflows/setup-js@ea00b206fd53ae8f6d75c72fb1f67b8673ab8959
        with:
          node-version: '24'
          package-manager: pnpm
      - name: Build admin
        run: pnpm --filter @yunzhen/app-admin build
        env:
          VITE_BASE_URL: /starter-react/
      - name: Add SPA fallback
        run: cp apps/admin/dist/index.html apps/admin/dist/404.html
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: apps/admin/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
